### ISSUE TITLE
Distorted Video

### ISSUE THREAD

**Issue by sourabhsingh29** [Wifsimster/node-rtsp-stream-es6#3]
<img width="1285" alt="screen shot 2018-01-29 at 4 41 36 pm" src="https://user-images.githubusercontent.com/19701369/35507616-602647e4-0513-11e8-95af-0fc5a4ae9e7c.png">

Live rtsp stream from ip-camera

**Comment by insolite** [comment]
OK, after ~1 hour of debugging and comparing `node-rtsp-stream-es6` with `node-rtsp-stream` I've found that in my case distortions are degrading each time I reconnect to the WebSocket. And there's a reason for that. The handler for `camdata` event is adding on each WS connect and never removed/replaced. Actually it should be added once on server creation (as in original `node-rtsp-stream`).

**Comment by Wifsimster** [comment]
Thanks for the comments. I hope i'll have time in the next weeks to take a look at this.
